name: auto lint and format with ruff
on: [push]
jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: linter
        uses: astral-sh/ruff-action@v3
      - name: formater
        run: ruff format
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: auto format with ruff"
