name: auto lint and format with ruff
on: [push]
jobs:
  Format-and-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format
