name: "Coverage and test with uv"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install UV
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run -m unittest discover -s tests
      - name: Run coverage
        run: uv run -m coverage xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
